---


- name: Copy Kibana configuration.
  template:
    src: kibana5.yml.j2
    dest: "{{ kibana.config_path_map[kibana.major_version] }}/{{ kibana.config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
  become: true
  become_user: root

- block:
    - name: Ensure Systemd defaults are in place
      become: yes
      template:
        src: kibana.defaultenv.j2
        dest: /etc/default/kibana
        mode: '0764'
      notify:
        - restart kibana

    - name: Ensure Systemd Service Configuration
      become: yes
      template:
        src: kibana.systemd.j2
        dest: /etc/systemd/system/kibana.service
        mode: '0764'
      notify:
        - start kibana
  when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: Install Kibana service
  become: yes
  template:
    src: kibana.service.conf.j2
    dest: /etc/init/kibana.conf
    mode: 764
  notify:
    - start kibana
  when: ansible_service_mgr is not defined or ansible_service_mgr != 'systemd'

- name: Enable Kibana service
  become: yes
  service:
    name: kibana
    enabled: yes
  notify:
    - start kibana

- block:
    - name: Check for kibana log
      stat:
        path: "{{ kibana.log_dest }}"
      become: true
      register: kibanalog

    - name: Touch kibana log - needs to exist
      file:
        path: "{{ kibana.log_dest }}"
        state: touch
        owner: "{{kibana.run_user}}"
        group: "{{ kibana.run_group }}"
        mode: 0640
      when: kibanalog.stat.exists == false
      notify:
        - restart kibana
  become: true
  when: kibana.log

- name: configure Kibana log rotation
  template:
    src: kibana.logrotate.j2
    dest: /etc/logrotate.d/kibana
    owner: root
    group: root
    mode: 0644
  when: kibana.log
  become: true
