---

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present


- name: Install Kibana plugins
  become: yes
  command: "{{ kibana.install_dir }}/bin/kibana plugin --install {{ item.plugin_name }}"
  args:
    chdir: "{{ kibana.install_dir }}"
    creates: "{{ kibana.install_dir }}/installedPlugins/{{ item.plugin_dir }}"
  environment:
    JAVA_HOME: /usr/share/java
  with_items: "{{ kibana.plugins }}"



- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes