---
- name: Ensure dependency is installed.
  apt:
    name: "{{item.package}}"
    state: "{{ item.state }}"
  with_items: "{{ kibana.dependencies }}"

- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ elasticsearch.gpg_key }}"
    state: present

- name: Add Kibana repository.
  apt_repository:
    repo: "{{ kibana.apt_repo_map[kibana.major_version] }}"
    state: present
    update_cache: yes

